---
- name: Ensure that the rssh package is installed
  tags: rssh
  become: true
  yum:
    enablerepo: epel-testing
    name: rssh
    state: present
  register: rssh_yum

- block:
  - name: Applying shell configuration into /etc/shells
    lineinfile:
      dest: /etc/shells
      line: '/usr/bin/rssh'
      owner: root
      group: root
      mode: 0644

  - name: Applying rssh.conf configurations
    template:
      src: rssh.conf.j2
      dest: /etc/rssh.conf
      owner: root
      group: root
      mode: 0644
  tags: rssh
  become: true
  when: rssh_yum|success
...
